const OFFLINE_APP_REVISION=(()=>{const meta=document.querySelector('meta[name="app-asset-revision"]');return meta&&meta.content?meta.content.trim():"1.2.0-r1";})();
const OFFLINE_MESSAGE_TIMEOUT_MS=4500;
const SAFE_UPDATE_SCREENS=new Set(["mainMenu","dashboard"]);
let offlineRegistration=null,deferredInstallPrompt=window.__cmsDeferredInstallPrompt||null,activationRequested=false,controllerReloaded=false,offlineUI=null,installPromptCaptured=Boolean(deferredInstallPrompt),installedStandalone=false;
function isStandaloneDisplay(){return Boolean((typeof matchMedia==="function"&&matchMedia("(display-mode: standalone)").matches)||navigator.standalone===true);}
function getActiveApplicationScreen(){return typeof window.getActiveScreenName==="function"?window.getActiveScreenName():document.querySelector(".screen:not(.hidden)")?.id||"";}
function getUpdateBoundaryStatus(){const screen=getActiveApplicationScreen(),restoreBusy=Boolean(document.querySelector('[data-transaction-busy="true"],[data-critical-recovery="true"]')),uiBusy=Boolean(document.querySelector('[aria-busy="true"]:not(#loadingScreen):not(#offlineAppRail)'));return{safe:SAFE_UPDATE_SCREENS.has(screen)&&!restoreBusy&&!uiBusy,screen,restoreBusy,uiBusy};}
function ensureOfflineStyles(){if(document.querySelector('link[data-offline-app-style="true"]'))return;const link=document.createElement("link");link.rel="stylesheet";link.href=`css/offline.css?v=${OFFLINE_APP_REVISION}`;link.dataset.offlineAppStyle="true";document.head.appendChild(link);}
function ensureOfflineUI(){if(offlineUI)return offlineUI;const rail=document.createElement("div");rail.id="offlineAppRail";rail.className="offlineAppRail";rail.setAttribute("role","region");rail.setAttribute("aria-label","Install and offline application status");const state=document.createElement("span");state.className="offlineAppState";state.id="offlineAppState";state.setAttribute("role","status");state.setAttribute("aria-live","polite");const install=document.createElement("button");install.type="button";install.className="offlineAppAction";install.id="offlineInstallAction";install.textContent="INSTALL INFO";const update=document.createElement("button");update.type="button";update.className="offlineAppAction offlineAppUpdate";update.id="offlineUpdateAction";update.textContent="UPDATE READY";update.hidden=true;rail.append(state,install,update);const panel=document.createElement("section");panel.id="offlineAppPanel";panel.className="offlineAppPanel";panel.hidden=true;panel.setAttribute("aria-labelledby","offlineAppPanelTitle");const heading=document.createElement("h2");heading.id="offlineAppPanelTitle";heading.textContent="INSTALL SHOWDOWN 17";const copy=document.createElement("p");copy.id="offlineAppPanelCopy";const actions=document.createElement("div");actions.className="offlineAppPanelActions";const close=document.createElement("button");close.type="button";close.className="offlineAppAction";close.textContent="CLOSE";close.addEventListener("click",()=>{panel.hidden=true;install.focus();});actions.append(close);panel.append(heading,copy,actions);document.body.append(rail,panel);install.addEventListener("click",handleInstallAction);update.addEventListener("click",activateWaitingUpdate);offlineUI={rail,state,install,update,panel,heading,copy,actions,close};return offlineUI;}
function getInstallGuidance(){const ua=navigator.userAgent||"",isiOS=/iPad|iPhone|iPod/i.test(ua)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1);if(isiOS)return "In Safari, use Share, then Add to Home Screen. Your tracker remains local to this device and the installed app can reopen its cached shell offline.";if(/Android|CrOS/i.test(ua))return "Use your browser's Install app command if the install prompt is not shown here. On ChromeOS and Android it is usually available from the address bar or browser menu.";return "Use your browser's Install app or Add to Home Screen command if available. Installation support and menu wording vary by browser.";}
function refreshInstallAction(){const ui=ensureOfflineUI();installedStandalone=isStandaloneDisplay();if(installedStandalone){ui.install.hidden=true;ui.panel.hidden=true;return;}ui.install.hidden=false;ui.install.textContent=deferredInstallPrompt?"INSTALL APP":"INSTALL INFO";}
async function handleInstallAction(){const ui=ensureOfflineUI();if(deferredInstallPrompt){const prompt=deferredInstallPrompt;deferredInstallPrompt=null;refreshInstallAction();try{await prompt.prompt();await prompt.userChoice;}catch(error){window.reportApplicationError?.("The browser install prompt could not be opened",error);}return;}ui.heading.textContent="INSTALL SHOWDOWN 17";ui.copy.textContent=getInstallGuidance();ui.panel.hidden=false;ui.close.focus();}
function setMenuMediaOfflineState(offline){const toggle=document.getElementById("menuMusicToggle"),status=document.getElementById("menuMusicStatus");if(offline){try{if(window.isMenuMediaPlaying?.()&&typeof window.toggleMenuMusic==="function")window.toggleMenuMusic();window.destroyMenuMediaIframe?.();}catch(error){console.warn("[Career Mode Showdown] External media cleanup failed while entering offline mode:",error);}if(toggle){toggle.disabled=true;toggle.setAttribute("aria-disabled","true");}if(status)status.textContent="OFFLINE · YOUTUBE MEDIA REQUIRES A CONNECTION";return;}if(toggle){toggle.disabled=false;toggle.removeAttribute("aria-disabled");}window.updateMenuMediaControls?.();}
function refreshConnectivity(){const ui=ensureOfflineUI(),offline=navigator.onLine===false;ui.rail.dataset.connectivity=offline?"offline":"online";ui.state.textContent=offline?"OFFLINE · LOCAL TRACKER READY":"ONLINE · OFFLINE SHELL READY";setMenuMediaOfflineState(offline);}
function markUpdateReady(){const ui=ensureOfflineUI();if(!offlineRegistration?.waiting){ui.update.hidden=true;return;}ui.update.hidden=false;ui.update.textContent="UPDATE READY";}
function sendWorkerMessage(worker,type,payload={}){return new Promise((resolve,reject)=>{if(!worker){reject(new Error("No service worker is available for this request."));return;}const channel=new MessageChannel(),timeout=window.setTimeout(()=>{channel.port1.close();reject(new Error(`Service worker message timed out: ${type}`));},OFFLINE_MESSAGE_TIMEOUT_MS);channel.port1.onmessage=event=>{window.clearTimeout(timeout);channel.port1.close();resolve(event.data||{});};worker.postMessage({type,...payload},[channel.port2]);});}
async function activateWaitingUpdate(){const waiting=offlineRegistration?.waiting;if(!waiting){markUpdateReady();return false;}const boundary=getUpdateBoundaryStatus();if(!boundary.safe){const message=boundary.restoreBusy||boundary.uiBusy?"Update is ready, but an application operation is still in progress. Finish it and return to Home or Showdown Home before updating.":"Update is ready. Return to Home or Showdown Home before applying it so unsaved form work is never discarded.";window.showAppNotice?.(message,"error",8000);return false;}const ui=ensureOfflineUI();ui.update.disabled=true;ui.update.textContent="VERIFYING UPDATE";try{const response=await sendWorkerMessage(waiting,"CMS_ACTIVATE_UPDATE",{pageRevision:OFFLINE_APP_REVISION,screen:boundary.screen});if(!response.ok||response.type!=="CMS_ACTIVATION_ACCEPTED")throw new Error(response.error||`Cached update is incomplete${Array.isArray(response.missing)&&response.missing.length?`: ${response.missing.join(", ")}`:"."}`);activationRequested=true;ui.update.textContent="APPLYING UPDATE";return true;}catch(error){ui.update.disabled=false;ui.update.textContent="UPDATE READY";window.reportApplicationError?.("The update was not activated because its offline shell could not be verified",error);return false;}}
function observeRegistration(registration){offlineRegistration=registration;markUpdateReady();registration.addEventListener("updatefound",()=>{const installing=registration.installing;if(!installing)return;installing.addEventListener("statechange",()=>{if(installing.state==="installed"&&navigator.serviceWorker.controller)markUpdateReady();});});}
async function registerOfflineApplication(){if(!("serviceWorker" in navigator))return null;const registration=await navigator.serviceWorker.register(`service-worker.js?v=${OFFLINE_APP_REVISION}`,{scope:"./",updateViaCache:"none"});observeRegistration(registration);try{await registration.update();}catch(error){if(navigator.onLine!==false)console.warn("[Career Mode Showdown] Service worker update check could not complete:",error);}return registration;}
function consumeEarlyInstallPrompt(){if(window.__cmsDeferredInstallPrompt){deferredInstallPrompt=window.__cmsDeferredInstallPrompt;window.__cmsDeferredInstallPrompt=null;installPromptCaptured=true;}}
function initializeOfflineApplication(){ensureOfflineStyles();ensureOfflineUI();consumeEarlyInstallPrompt();refreshInstallAction();refreshConnectivity();window.addEventListener("online",refreshConnectivity);window.addEventListener("offline",refreshConnectivity);window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstallPrompt=event;installPromptCaptured=true;refreshInstallAction();});window.addEventListener("appinstalled",()=>{deferredInstallPrompt=null;installedStandalone=true;refreshInstallAction();window.showAppNotice?.("Career Mode Showdown is installed and ready for local offline use.","success",5500);});if("serviceWorker" in navigator){navigator.serviceWorker.addEventListener("controllerchange",()=>{if(activationRequested&&!controllerReloaded){controllerReloaded=true;window.location.reload();}});registerOfflineApplication().catch(error=>window.reportApplicationError?.("Offline application support could not be prepared",error));}}
window.getOfflineAppDiagnostics=()=>({revision:OFFLINE_APP_REVISION,supported:"serviceWorker" in navigator,registration:Boolean(offlineRegistration),waiting:Boolean(offlineRegistration?.waiting),connectivity:navigator.onLine===false?"offline":"online",standalone:isStandaloneDisplay(),installPromptCaptured,safeUpdateBoundary:getUpdateBoundaryStatus()});window.getOfflineUpdateBoundaryStatus=getUpdateBoundaryStatus;window.activateWaitingOfflineUpdate=activateWaitingUpdate;initializeOfflineApplication();
