(function(root,factory){
  const api=factory(root);
  if(typeof module!=="undefined"&&module.exports)module.exports=api;
  else root.CareerModePersistentNikDanielPair=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";

  const PAIR_DOC_ID="current";
  const MANAGER_BY_ROLE=Object.freeze({playerOne:Object.freeze({id:"nik",label:"Nik"}),playerTwo:Object.freeze({id:"daniel",label:"Daniel"})});
  const ROLE_BY_MANAGER=Object.freeze({nik:"playerOne",daniel:"playerTwo"});
  const PANEL_ID="persistentNikDanielPairPanel";
  const CODE_INPUT_ID="persistentNikDanielPairCode";
  const CONNECTED_RIVALRY_PATH="js/sparkConnectedRivalry.js";
  let state=Object.freeze({status:"idle",initialized:false,busy:false,accountId:null,deviceId:null,managerRole:null,managerId:null,rivalryId:null,connectionState:null,capability:null,message:"Preparing the Nik and Daniel online pair…"});
  let initializePromise=null;
  let connectedRivalryLoadPromise=null;
  const listeners=new Set();

  function freezeDeep(value){if(!value||typeof value!=="object"||Object.isFrozen(value))return value;Object.freeze(value);Object.values(value).forEach(freezeDeep);return value;}
  function setState(next){state=freezeDeep({...state,...next});for(const listener of listeners){try{listener(state);}catch(_error){}}render();return state;}
  function errorWithCode(code,message){const error=new Error(message||code);error.code=code;return error;}
  function asResultError(error,fallback){return{ok:false,code:error&&typeof error.code==="string"?error.code:fallback,message:error&&error.message?error.message:"The persistent online pair operation could not be completed."};}
  function canonicalize(value){if(value===null||value===undefined)return value===undefined?null:value;if(value&&typeof value.toMillis==="function")return{$timestamp:value.toMillis()};if(Array.isArray(value))return value.map(canonicalize);if(typeof value==="object"){const result={};for(const key of Object.keys(value).sort())result[key]=canonicalize(value[key]);return result;}return value;}
  function hexFromBytes(bytes){return Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("");}
  async function sha256(value,cryptoImpl=root.crypto){if(!cryptoImpl?.subtle||typeof cryptoImpl.subtle.digest!=="function")throw errorWithCode("PERSISTENT_PAIR_CRYPTO_UNAVAILABLE","Secure browser hashing is unavailable.");const bytes=new TextEncoder().encode(JSON.stringify(canonicalize(value)));const digest=await cryptoImpl.subtle.digest("SHA-256",bytes);return`sha256:${hexFromBytes(new Uint8Array(digest))}`;}
  async function buildEnvelope({objectId=PAIR_DOC_ID,revision,parentRevision,priorContentHash,updatedAt,updatedByAccountId,updatedByDeviceId,data,cryptoImpl=root.crypto}){const contentHash=await sha256({objectType:"pairLink",objectId,revision,data},cryptoImpl);return{schemaVersion:1,objectType:"pairLink",objectId,revision,parentRevision,lifecycleState:"live",contentHash,priorContentHash,updatedAt,updatedByAccountId,updatedByDeviceId,data,tombstone:null};}
  function normalizeRivalryId(value){const id=typeof value==="string"?value.trim().toLowerCase():"";if(!/^pair_[0-9a-f]{64}$/.test(id))throw errorWithCode("PERSISTENT_PAIR_RIVALRY_INVALID","The online rivalry identity is invalid.");return id;}
  function normalizeManagerRole(value){const role=typeof value==="string"?value.trim():"";if(!MANAGER_BY_ROLE[role])throw errorWithCode("PERSISTENT_PAIR_ROLE_INVALID","Choose Nik or Daniel before pairing.");return role;}
  function managerForRole(role){return MANAGER_BY_ROLE[normalizeManagerRole(role)];}
  function currentIdentityRole(){const identity=root.CareerModeOnlinePlayerIdentity?.getState?.();if(identity?.managerId&&ROLE_BY_MANAGER[identity.managerId])return ROLE_BY_MANAGER[identity.managerId];return null;}
  function localBindingForRole(pairing,role){const normalized=normalizeManagerRole(role);const bindings=pairing&&typeof pairing.localBindingOptions==="function"?pairing.localBindingOptions():[];return(Array.isArray(bindings)?bindings:[]).find(binding=>binding&&binding.managerRole===normalized)||null;}
  function pairLinkReference(context){return context.services.firestoreSdk.doc(context.services.firestore,"accounts",context.accountId,"pairLinks",PAIR_DOC_ID);}
  function rivalryReference(context,rivalryId){return context.services.firestoreSdk.doc(context.services.firestore,"rivalries",rivalryId);}
  function deviceReference(context){return context.services.firestoreSdk.doc(context.services.firestore,"accounts",context.accountId,"devices",context.deviceId);}
  function isEnvelopeValue(value,objectType,objectId){return Boolean(value&&value.schemaVersion===1&&value.objectType===objectType&&value.objectId===objectId&&value.lifecycleState==="live"&&Number.isInteger(value.revision)&&value.revision>=0&&typeof value.contentHash==="string");}
  function assertActiveDevice(snapshot,deviceId){if(!snapshot?.exists?.())throw errorWithCode("PERSISTENT_PAIR_DEVICE_REQUIRED","This browser is not registered.");const value=snapshot.data();if(!isEnvelopeValue(value,"device",deviceId)||value.data?.deviceId!==deviceId||value.data?.state!=="active")throw errorWithCode("PERSISTENT_PAIR_DEVICE_REQUIRED","This browser is not an active registered device.");return value;}
  function rivalrySlotFor(value,accountId){if(!isEnvelopeValue(value,"rivalry",value?.objectId)||!Array.isArray(value.data?.managerSlots))return null;return value.data.managerSlots.find(slot=>slot&&slot.accountId===accountId)||null;}
  function assertRivalryMembership(value,rivalryId,accountId,expectedRole=null){if(!isEnvelopeValue(value,"rivalry",rivalryId))throw errorWithCode("PERSISTENT_PAIR_RIVALRY_MISSING","The linked online rivalry is unavailable.");if(!["pending-pair","active"].includes(value.data?.connectionState))throw errorWithCode("PERSISTENT_PAIR_RIVALRY_INACTIVE","The linked online rivalry is no longer pairable or active.");const slot=rivalrySlotFor(value,accountId);if(!slot||!MANAGER_BY_ROLE[slot.slotId])throw errorWithCode("PERSISTENT_PAIR_MEMBERSHIP_MISSING","This account is not a manager in the linked online rivalry.");if(expectedRole&&slot.slotId!==expectedRole)throw errorWithCode("PERSISTENT_PAIR_ROLE_CONFLICT","This account is already bound to the other manager role.");return{slot,connectionState:value.data.connectionState};}
  function parsePairLink(value,accountId){if(!isEnvelopeValue(value,"pairLink",PAIR_DOC_ID))throw errorWithCode("PERSISTENT_PAIR_LINK_INVALID","The persistent pair record is invalid.");const data=value.data||{},role=normalizeManagerRole(data.managerRole),manager=managerForRole(role),rivalryId=normalizeRivalryId(data.rivalryId);if(data.managerId!==manager.id)throw errorWithCode("PERSISTENT_PAIR_ROLE_CONFLICT","The persistent manager identity is inconsistent.");return{accountId,rivalryId,managerRole:role,managerId:manager.id,managerLabel:manager.label,revision:value.revision,contentHash:value.contentHash,linkedAt:data.linkedAt,lastConfirmedAt:data.lastConfirmedAt};}
  async function resolveContext(){const runtime=root.CareerModeProductionFirebaseRuntime,account=root.CareerModeSparkConnectedAccount,pairing=root.CareerModeSparkPrivatePairing;if(!runtime||!account||!pairing)throw errorWithCode("PERSISTENT_PAIR_RUNTIME_UNAVAILABLE","Online pair dependencies are unavailable.");await account.initialize();const accountState=account.getState?.();if(!accountState?.connected||!accountState.accountId)throw errorWithCode("PERSISTENT_PAIR_AUTH_REQUIRED","Sign in before using the online pair.");await pairing.initialize();const pairingState=pairing.getState?.();if(!pairingState?.registered||!pairingState.deviceId)throw errorWithCode("PERSISTENT_PAIR_DEVICE_REQUIRED","Register this browser before using the online pair.");const services=await runtime.ensureAccountServices();const user=services?.auth?.currentUser;if(!services?.ok||!user||user.uid!==accountState.accountId)throw errorWithCode("PERSISTENT_PAIR_AUTH_REQUIRED","The signed-in account is unavailable.");return{runtime,account,pairing,services,user,accountId:accountState.accountId,deviceId:pairingState.deviceId};}
  async function readPairLink(context){const sdk=context.services.firestoreSdk,ref=pairLinkReference(context);return sdk.runTransaction(context.services.firestore,async transaction=>{const pairSnapshot=await transaction.get(ref);if(!pairSnapshot.exists())return null;const link=parsePairLink(pairSnapshot.data(),context.accountId),rivalrySnapshot=await transaction.get(rivalryReference(context,link.rivalryId));if(!rivalrySnapshot.exists())throw errorWithCode("PERSISTENT_PAIR_RIVALRY_MISSING","The linked online rivalry is unavailable.");const membership=assertRivalryMembership(rivalrySnapshot.data(),link.rivalryId,context.accountId,link.managerRole);return{...link,connectionState:membership.connectionState};});}
  async function persistPairLink(context,rivalryId,managerRole){const sdk=context.services.firestoreSdk,role=normalizeManagerRole(managerRole),manager=managerForRole(role),normalizedRivalryId=normalizeRivalryId(rivalryId),pairRef=pairLinkReference(context),rivalryRef=rivalryReference(context,normalizedRivalryId),deviceRef=deviceReference(context),now=sdk.Timestamp.fromMillis(Date.now());return sdk.runTransaction(context.services.firestore,async transaction=>{const deviceSnapshot=await transaction.get(deviceRef);assertActiveDevice(deviceSnapshot,context.deviceId);const rivalrySnapshot=await transaction.get(rivalryRef);if(!rivalrySnapshot.exists())throw errorWithCode("PERSISTENT_PAIR_RIVALRY_MISSING","The online rivalry could not be confirmed.");const membership=assertRivalryMembership(rivalrySnapshot.data(),normalizedRivalryId,context.accountId,role),pairSnapshot=await transaction.get(pairRef);let revision=0,parentRevision=null,priorContentHash=null,linkedAt=now;if(pairSnapshot.exists()){const existing=parsePairLink(pairSnapshot.data(),context.accountId);if(existing.managerRole!==role)throw errorWithCode("PERSISTENT_PAIR_ROLE_CONFLICT",`${manager.label} is not the manager role already bound to this account.`);if(existing.rivalryId!==normalizedRivalryId){const oldSnapshot=await transaction.get(rivalryReference(context,existing.rivalryId));if(oldSnapshot.exists()&&oldSnapshot.data()?.data?.connectionState==="active")throw errorWithCode("PERSISTENT_PAIR_ACTIVE_CONFLICT","This account already has an active Nik and Daniel pair.");}revision=existing.revision+1;parentRevision=existing.revision;priorContentHash=existing.contentHash;linkedAt=existing.linkedAt||now;}const data={rivalryId:normalizedRivalryId,managerRole:role,managerId:manager.id,linkedAt,lastConfirmedAt:now};const envelope=await buildEnvelope({revision,parentRevision,priorContentHash,updatedAt:now,updatedByAccountId:context.accountId,updatedByDeviceId:context.deviceId,data});transaction.set(pairRef,envelope);return{rivalryId:normalizedRivalryId,managerRole:role,managerId:manager.id,managerLabel:manager.label,connectionState:membership.connectionState,revision:envelope.revision};});}
  async function loadConnectedRivalry(){if(root.CareerModeSparkConnectedRivalry)return root.CareerModeSparkConnectedRivalry;if(connectedRivalryLoadPromise)return connectedRivalryLoadPromise;if(typeof root.loadRuntimeScript!=="function")return null;connectedRivalryLoadPromise=root.loadRuntimeScript("persistent-pair-connected-rivalry",CONNECTED_RIVALRY_PATH,()=>Boolean(root.CareerModeSparkConnectedRivalry)).then(()=>root.CareerModeSparkConnectedRivalry||null).catch(()=>null).finally(()=>{connectedRivalryLoadPromise=null;});return connectedRivalryLoadPromise;}
  async function migrateExistingConnectedRivalry(context){const connected=await loadConnectedRivalry();if(!connected?.initialize)return null;await connected.initialize();const current=connected.getState?.();if(!current?.attached||!current.rivalryId||!current.binding?.managerRole)return null;try{return await persistPairLink(context,current.rivalryId,current.binding.managerRole);}catch(_error){return null;}}
  async function initialize(options={}){if(initializePromise&&!options.force)return initializePromise;initializePromise=(async()=>{try{const context=await resolveContext();let link=await readPairLink(context);if(!link&&options.migrate!==false){const migrated=await migrateExistingConnectedRivalry(context);if(migrated)link=await readPairLink(context);}if(!link)return setState({status:"unpaired",initialized:true,busy:false,accountId:context.accountId,deviceId:context.deviceId,managerRole:null,managerId:null,rivalryId:null,connectionState:null,capability:null,message:"Nik and Daniel are not permanently paired yet. The existing one-use code is needed only for this first bootstrap."});return setState({status:link.connectionState==="active"?"paired":"waiting",initialized:true,busy:false,accountId:context.accountId,deviceId:context.deviceId,managerRole:link.managerRole,managerId:link.managerId,rivalryId:link.rivalryId,connectionState:link.connectionState,capability:link.connectionState==="pending-pair"?link.rivalryId:null,message:link.connectionState==="active"?`${link.managerLabel} is permanently linked to the Nik and Daniel online rivalry on this account.`:`${link.managerLabel} is waiting for the other manager to join. This first bootstrap code can be reused only until it is redeemed or expires.`});}catch(error){return setState({status:error?.code==="PERSISTENT_PAIR_AUTH_REQUIRED"?"signed-out":"unavailable",initialized:true,busy:false,accountId:null,deviceId:null,managerRole:null,managerId:null,rivalryId:null,connectionState:null,capability:null,message:error?.message||"Persistent online pair is unavailable."});}})().finally(()=>{initializePromise=null;});return initializePromise;}
  function selectedRole(){return state.managerRole||currentIdentityRole();}
  async function startPairing(options={}){if(state.busy)return state;setState({status:"starting",busy:true,message:"Creating the first private Nik and Daniel pairing code…"});try{const context=await resolveContext(),role=normalizeManagerRole(options.managerRole||selectedRole()),binding=localBindingForRole(context.pairing,role);if(!binding)throw errorWithCode("PERSISTENT_PAIR_SAVE_REQUIRED","Create or restore the local Save Library identity for this manager before the first pairing bootstrap.");if(state.connectionState==="active"&&state.rivalryId)return setState({status:"paired",busy:false,message:"Nik and Daniel are already paired. No new code is required."});const result=await context.pairing.createPairing({user:context.user,firestore:context.services.firestore,firebaseSdk:context.services.firestoreSdk,identity:await context.pairing.getOrCreateDeviceIdentity({indexedDBImpl:root.indexedDB,cryptoImpl:root.crypto}),binding,cryptoImpl:root.crypto});if(!result?.ok)throw errorWithCode(result?.code||"PERSISTENT_PAIR_CREATE_FAILED",result?.message||"The pairing code could not be created.");const link=await persistPairLink(context,result.rivalryId,role);return setState({status:"waiting",initialized:true,busy:false,accountId:context.accountId,deviceId:context.deviceId,managerRole:role,managerId:managerForRole(role).id,rivalryId:link.rivalryId,connectionState:"pending-pair",capability:result.capability,message:`Pairing code ready. Send it once to ${role==="playerOne"?"Daniel":"Nik"}. After the first join, future browsers recover the pair from the account automatically.`});}catch(error){return setState({status:error?.code==="PERSISTENT_PAIR_SAVE_REQUIRED"?"save-required":"error",busy:false,message:error?.message||"The first pairing bootstrap could not be started."});}}
  async function joinPairing(capability,options={}){if(state.busy)return state;setState({status:"joining",busy:true,message:"Joining the permanent Nik and Daniel pair…"});try{const context=await resolveContext(),role=normalizeManagerRole(options.managerRole||selectedRole()),binding=localBindingForRole(context.pairing,role);if(!binding)throw errorWithCode("PERSISTENT_PAIR_SAVE_REQUIRED","Create or restore the local Save Library identity for this manager before joining the first pair.");const result=await context.pairing.redeemPairing({user:context.user,firestore:context.services.firestore,firebaseSdk:context.services.firestoreSdk,identity:await context.pairing.getOrCreateDeviceIdentity({indexedDBImpl:root.indexedDB,cryptoImpl:root.crypto}),binding,capability,cryptoImpl:root.crypto});if(!result?.ok)throw errorWithCode(result?.code||"PERSISTENT_PAIR_JOIN_FAILED",result?.message||"The pairing code could not be joined.");const link=await persistPairLink(context,result.rivalryId,role);return setState({status:"paired",initialized:true,busy:false,accountId:context.accountId,deviceId:context.deviceId,managerRole:role,managerId:managerForRole(role).id,rivalryId:link.rivalryId,connectionState:"active",capability:null,message:`${managerForRole(role).label} is connected. This account will recover the same Nik and Daniel pair on future registered browsers without another pairing code.`});}catch(error){return setState({status:error?.code==="PERSISTENT_PAIR_SAVE_REQUIRED"?"save-required":"error",busy:false,message:contextualJoinMessage(error)});}}
  function contextualJoinMessage(error){const pairing=root.CareerModeSparkPrivatePairing;if(pairing&&typeof pairing.pairingJoinErrorMessage==="function")return pairing.pairingJoinErrorMessage(error);return error?.message||"The pairing code could not be joined.";}
  async function continuePair(){if(state.busy||!state.rivalryId)return state;setState({status:"continuing",busy:true,message:"Opening the existing shared rivalry…"});try{const context=await resolveContext(),role=normalizeManagerRole(state.managerRole||selectedRole()),binding=localBindingForRole(context.pairing,role);if(!binding)throw errorWithCode("PERSISTENT_PAIR_LOCAL_RECOVERY_REQUIRED","This account is paired, but this browser needs the matching local Save Library identity before gameplay can continue.");const connected=await loadConnectedRivalry();if(!connected?.attachRivalry)throw errorWithCode("PERSISTENT_PAIR_CONNECTED_RIVALRY_UNAVAILABLE","Connected Rivalry is unavailable.");const result=await connected.attachRivalry({user:context.user,firestore:context.services.firestore,firebaseSdk:context.services.firestoreSdk,deviceId:context.deviceId,binding,rivalryId:state.rivalryId,indexedDBImpl:root.indexedDB});if(!result?.ok)throw errorWithCode(result?.code||"PERSISTENT_PAIR_ATTACH_FAILED",result?.message||"The shared rivalry could not be opened.");await connected.initialize();root.showScreen?.("dashboard");return setState({status:"paired",busy:false,connectionState:"active",message:"Nik and Daniel are connected. The existing shared rivalry is attached on this browser."});}catch(error){return setState({status:error?.code==="PERSISTENT_PAIR_LOCAL_RECOVERY_REQUIRED"?"recovery-required":"error",busy:false,message:error?.message||"The existing shared rivalry could not be opened."});}}
  function createElement(tag,className,text){const element=root.document.createElement(tag);if(className)element.className=className;if(text!==undefined&&text!==null)element.textContent=String(text);return element;}
  function copyText(value){if(root.navigator?.clipboard?.writeText)return root.navigator.clipboard.writeText(value).then(()=>true).catch(()=>false);return Promise.resolve(false);}
  function roleLabel(role){return role?managerForRole(role).label:(root.CareerModeOnlinePlayerIdentity?.getState?.().managerLabel||"PLAYER");}
  function render(){if(!root.document)return null;const shell=root.document.querySelector("#mainMenu .fifaMenuShell");if(!shell)return null;let panel=root.document.getElementById(PANEL_ID);if(!panel){panel=createElement("section","stateNote");panel.id=PANEL_ID;Object.assign(panel.style,{margin:"0 0 14px",padding:"14px 16px",border:"1px solid rgba(255,255,255,.16)",background:"rgba(5,10,17,.7)"});const grid=shell.querySelector(".fifaMenuGrid");shell.insertBefore(panel,grid||null);}panel.replaceChildren();const title=createElement("strong","",state.connectionState==="active"?"NIK + DANIEL CONNECTED":state.connectionState==="pending-pair"?"WAITING FOR THE OTHER MANAGER":"ONLINE SHOWDOWN PAIR");const message=createElement("p","",state.message);message.style.margin="6px 0 10px";panel.append(title,message);if(!state.accountId)return panel;const actions=createElement("div","");Object.assign(actions.style,{display:"flex",flexWrap:"wrap",gap:"8px",alignItems:"center"});if(state.status==="unpaired"||state.status==="save-required"||state.status==="error"){const start=createElement("button","menuButton","START PAIRING");start.type="button";start.disabled=state.busy;start.addEventListener("click",()=>void startPairing());const input=createElement("input","settingsConnectedAccountInput");input.id=CODE_INPUT_ID;input.type="text";input.placeholder="Paste first pairing code";input.autocomplete="off";input.spellcheck=false;input.style.minWidth="min(330px,100%)";const join=createElement("button","menuButton","JOIN PAIR");join.type="button";join.disabled=state.busy;join.addEventListener("click",()=>void joinPairing(input.value));actions.append(start,input,join);}else if(state.connectionState==="pending-pair"&&state.rivalryId){const code=createElement("code","",state.rivalryId),copy=createElement("button","menuButton","COPY FIRST CODE"),refresh=createElement("button","menuButton","CHECK JOIN STATUS");code.style.wordBreak="break-all";copy.type=refresh.type="button";copy.addEventListener("click",async()=>{const ok=await copyText(state.rivalryId);setState({message:ok?"Pairing code copied. It is needed only for this first bootstrap.":"Clipboard copy was unavailable. Select the full code shown here and copy it manually."});});refresh.addEventListener("click",()=>void initialize({force:true,migrate:false}));actions.append(code,copy,refresh);}else if(state.connectionState==="active"){const open=createElement("button","menuButton","CONTINUE ONLINE SHOWDOWN");open.type="button";open.disabled=state.busy;open.addEventListener("click",()=>void continuePair());actions.append(open,createElement("span","",`${roleLabel(state.managerRole)} · pair remembered by account`));}panel.append(actions);return panel;}
  function subscribe(listener){if(typeof listener!=="function")return()=>{};listeners.add(listener);return()=>listeners.delete(listener);}
  if(root.addEventListener){root.addEventListener("career-mode-online-identity-change",()=>render());root.addEventListener("online",()=>{if(state.initialized)void initialize({force:true});});}
  return freezeDeep({contractVersion:1,feature:"persistent-nik-daniel-pair",pairDocumentId:PAIR_DOC_ID,publicDiscovery:false,billingRequired:false,persistentAcrossRegisteredBrowsers:true,managerByRole:MANAGER_BY_ROLE,roleByManager:ROLE_BY_MANAGER,normalizeRivalryId,parsePairLink,readPairLink,persistPairLink,initialize,startPairing,joinPairing,continuePair,render,subscribe,getState:()=>state});
});