(function(root,factory){
  const protocol=typeof module!=="undefined"&&module.exports?require("./sharedTerminalClose.js"):root.CareerModeSharedTerminalClose;
  const sessionProtocol=typeof module!=="undefined"&&module.exports?require("./sparkPrivateSession.js"):root.CareerModeSparkPrivateSession;
  const api=factory(root,protocol,sessionProtocol);if(typeof module!=="undefined"&&module.exports)module.exports=api;else root.CareerModeSparkTerminalClose=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(root,protocol,sessionProtocol){
  "use strict";
  function stpFail(code,message){const error=new Error(message||code);error.code=code;throw error;}
  function stcResultError(error,fallback){return {ok:false,code:error&&typeof error.code==="string"?error.code:fallback,message:error&&error.message?error.message:"Terminal Close could not be completed."};}
  function stpClone(value){return JSON.parse(JSON.stringify(value));}
  function stpFreeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.values(value).forEach(stpFreeze);Object.freeze(value);}return value;}
  function stpCanonical(value){if(value===undefined||value===null)return null;if(value&&typeof value.toMillis==="function")return {$timestamp:value.toMillis()};if(value instanceof Date)return {$timestamp:value.getTime()};if(Array.isArray(value))return value.map(stpCanonical);if(typeof value==="object"){const out={};for(const key of Object.keys(value).sort())out[key]=stpCanonical(value[key]);return out;}return value;}
  function stcHex(bytes){return Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("");}
  async function stcHashEnvelopeValue(value,cryptoImpl=root.crypto){if(!cryptoImpl||!cryptoImpl.subtle||typeof cryptoImpl.subtle.digest!=="function")stpFail("TERMINAL_CLOSE_CRYPTO_UNAVAILABLE");const digest=await cryptoImpl.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(stpCanonical(value))));return `sha256:${stcHex(new Uint8Array(digest))}`;}
  function stcNormalizeId(value,pattern,code){const normalized=typeof value==="string"?value.trim().toLowerCase():"";if(!pattern.test(normalized))stpFail(code);return normalized;}
  function stcNormalizeAccount(user){const id=user&&typeof user.uid==="string"?user.uid.trim():"";if(!id)stpFail("TERMINAL_CLOSE_AUTH_REQUIRED");return id;}
  function stcSnapshotValue(snapshot){return snapshot&&typeof snapshot.exists==="function"&&snapshot.exists()?snapshot.data():null;}
  function stcEnvelopeShape(value,type,id){return Boolean(value&&value.schemaVersion===1&&value.objectType===type&&value.objectId===id&&Number.isInteger(value.revision)&&value.revision>=0&&value.lifecycleState==="live"&&typeof value.contentHash==="string"&&/^sha256:[0-9a-f]{64}$/.test(value.contentHash)&&value.data&&typeof value.data==="object"&&value.tombstone===null);}
  async function stcVerifyEnvelope(value,type,id,cryptoImpl){if(!stcEnvelopeShape(value,type,id))stpFail("TERMINAL_CLOSE_AUTHORITY_INVALID");const expected=await stcHashEnvelopeValue({objectType:type,objectId:id,revision:value.revision,data:value.data},cryptoImpl);if(expected!==value.contentHash)stpFail("TERMINAL_CLOSE_INTEGRITY_FAILED");return value;}
  function stcAssertActiveAccount(value,accountId){if(!stcEnvelopeShape(value,"account",accountId)||value.data.status!=="active")stpFail("TERMINAL_CLOSE_ACCOUNT_INACTIVE");}
  function stcAssertActiveDevice(value,deviceId){if(!stcEnvelopeShape(value,"device",deviceId)||value.data.deviceId!==deviceId||value.data.state!=="active")stpFail(value&&value.data&&value.data.state==="revoked"?"TERMINAL_CLOSE_DEVICE_REVOKED":"TERMINAL_CLOSE_DEVICE_INACTIVE");}
  function stcValidateSdk(firestore,sdk){if(!firestore)stpFail("TERMINAL_CLOSE_PROVIDER_UNAVAILABLE");for(const method of ["doc","runTransaction"]){if(!sdk||typeof sdk[method]!=="function")stpFail("TERMINAL_CLOSE_PROVIDER_UNAVAILABLE");}if(!sdk.Timestamp||typeof sdk.Timestamp.fromMillis!=="function")stpFail("TERMINAL_CLOSE_PROVIDER_UNAVAILABLE");}
  function stcNormalizeOptions(options={}){
    stcValidateSdk(options.firestore,options.firebaseSdk);if(!protocol||typeof protocol.verifyIntent!=="function"||!sessionProtocol||typeof sessionProtocol.verifySession!=="function"||typeof sessionProtocol.buildEnvelope!=="function")stpFail("TERMINAL_CLOSE_DEPENDENCY_UNAVAILABLE");
    const intent=protocol.verifyIntent(options.intent),rivalryId=stcNormalizeId(options.rivalryId,/^pair_[0-9a-f]{64}$/,"TERMINAL_CLOSE_RIVALRY_INVALID"),sessionId=stcNormalizeId(options.sessionId,/^session_[0-9a-f]{64}$/,"TERMINAL_CLOSE_SESSION_INVALID");
    if(intent.rivalryId!==rivalryId)stpFail("TERMINAL_CLOSE_RIVALRY_MISMATCH");if(intent.sessionId!==sessionId)stpFail("TERMINAL_CLOSE_SESSION_MISMATCH");
    const nowEpochMs=options.nowEpochMs===undefined?Date.now():Number(options.nowEpochMs);if(!Number.isFinite(nowEpochMs)||nowEpochMs<=0)stpFail("TERMINAL_CLOSE_TIME_INVALID");
    return stpFreeze({firestore:options.firestore,firebaseSdk:options.firebaseSdk,accountId:stcNormalizeAccount(options.user),deviceId:stcNormalizeId(options.deviceId,/^device_[0-9a-f]{32}$/,"TERMINAL_CLOSE_DEVICE_INVALID"),rivalryId,sessionId,intent,nowEpochMs,cryptoImpl:options.cryptoImpl||root.crypto});
  }
  function stcRefs(operation){const sdk=operation.firebaseSdk,db=operation.firestore;return stpFreeze({account:sdk.doc(db,"accounts",operation.accountId),device:sdk.doc(db,"accounts",operation.accountId,"devices",operation.deviceId),rivalry:sdk.doc(db,"rivalries",operation.rivalryId),session:sdk.doc(db,"rivalries",operation.rivalryId,"sessions",operation.sessionId)});}
  function stcEntitledRivalry(rivalry,accountId){const ids=Array.isArray(rivalry.data.authorizedAccountIds)?rivalry.data.authorizedAccountIds:[],slots=Array.isArray(rivalry.data.managerSlots)?rivalry.data.managerSlots:[];if(ids.length!==2||new Set(ids).size!==2||!ids.includes(accountId)||slots.length!==2||slots.some(slot=>!slot||slot.entitlementState!=="active"||typeof slot.accountId!=="string")||!ids.every(id=>slots.some(slot=>slot.accountId===id)))stpFail("TERMINAL_CLOSE_RIVALRY_AUTHORITY_INVALID");return ids;}
  async function stcBuildRivalryEnvelope(operation,prior,data,now){const revision=prior.revision+1;return {schemaVersion:1,objectType:"rivalry",objectId:operation.rivalryId,revision,parentRevision:prior.revision,lifecycleState:"live",contentHash:await stcHashEnvelopeValue({objectType:"rivalry",objectId:operation.rivalryId,revision,data},operation.cryptoImpl),priorContentHash:prior.contentHash,updatedAt:now,updatedByAccountId:operation.accountId,updatedByDeviceId:operation.deviceId,data,tombstone:null};}
  function stcAccepted(operation,rivalry,session,replayed){return stpFreeze({ok:true,status:replayed?"replayed":"accepted",replayed:Boolean(replayed),rivalryId:operation.rivalryId,sessionId:operation.sessionId,rivalryState:"closed",sessionState:"closed",rivalryRevision:rivalry.revision,sessionRevision:session.revision,terminalWitness:stpClone(operation.intent),canonicalStorageMutation:false,listPermissionRequired:false,billingRequired:false});}
  async function stcClose(options={}){try{const operation=stcNormalizeOptions(options),references=stcRefs(operation);return await operation.firebaseSdk.runTransaction(operation.firestore,async transaction=>{
    const accountValue=stcSnapshotValue(await transaction.get(references.account));stcAssertActiveAccount(accountValue,operation.accountId);const deviceValue=stcSnapshotValue(await transaction.get(references.device));stcAssertActiveDevice(deviceValue,operation.deviceId);
    const rivalryValue=stcSnapshotValue(await transaction.get(references.rivalry));await stcVerifyEnvelope(rivalryValue,"rivalry",operation.rivalryId,operation.cryptoImpl);const authorized=stcEntitledRivalry(rivalryValue,operation.accountId);
    const sessionValue=stcSnapshotValue(await transaction.get(references.session));if(!sessionValue)stpFail("TERMINAL_CLOSE_SESSION_NOT_FOUND");const session=await sessionProtocol.verifySession(sessionValue,operation.rivalryId,operation.sessionId,operation.cryptoImpl);if(!session.members.includes(operation.accountId))stpFail("TERMINAL_CLOSE_SESSION_MEMBER_REQUIRED");
    if(rivalryValue.data.connectionState==="closed"){if(!protocol.sameWitness(rivalryValue.data.terminalClose,operation.intent))stpFail("TERMINAL_CLOSE_REPLAY_CONFLICT");if(session.data.state!=="closed")stpFail("TERMINAL_CLOSE_PARTIAL_STATE_INVALID");return stcAccepted(operation,rivalryValue,sessionValue,true);}
    if(rivalryValue.data.connectionState!=="active")stpFail("TERMINAL_CLOSE_RIVALRY_NOT_ACTIVE");if(session.data.state!=="active"||session.members.length!==2||authorized.some(id=>!session.members.includes(id)))stpFail("TERMINAL_CLOSE_SESSION_NOT_ACTIVE");if(operation.nowEpochMs>=session.expiresAtEpochMs)stpFail("TERMINAL_CLOSE_SESSION_EXPIRED");
    const now=operation.firebaseSdk.Timestamp.fromMillis(operation.nowEpochMs),sessionData={...session.data,state:"closed",lastActivityAt:now,revokedAt:null};const nextSession=await sessionProtocol.buildEnvelope({sessionId:operation.sessionId,revision:sessionValue.revision+1,parentRevision:sessionValue.revision,priorContentHash:sessionValue.contentHash,updatedAt:now,accountId:operation.accountId,deviceId:operation.deviceId,data:sessionData,cryptoImpl:operation.cryptoImpl});const rivalryData={...rivalryValue.data,connectionState:"closed",terminalClose:stpClone(operation.intent)},nextRivalry=await stcBuildRivalryEnvelope(operation,rivalryValue,rivalryData,now);transaction.set(references.session,nextSession);transaction.set(references.rivalry,nextRivalry);return stcAccepted(operation,nextRivalry,nextSession,false);
  });}catch(error){return stcResultError(error,"TERMINAL_CLOSE_FAILED");}}
  async function stcRead(options={}){try{stcValidateSdk(options.firestore,options.firebaseSdk);if(!protocol||typeof protocol.verifyIntent!=="function")stpFail("TERMINAL_CLOSE_DEPENDENCY_UNAVAILABLE");const accountId=stcNormalizeAccount(options.user),deviceId=stcNormalizeId(options.deviceId,/^device_[0-9a-f]{32}$/,"TERMINAL_CLOSE_DEVICE_INVALID"),rivalryId=stcNormalizeId(options.rivalryId,/^pair_[0-9a-f]{64}$/,"TERMINAL_CLOSE_RIVALRY_INVALID"),cryptoImpl=options.cryptoImpl||root.crypto,sdk=options.firebaseSdk,db=options.firestore;return await sdk.runTransaction(db,async transaction=>{stcAssertActiveAccount(stcSnapshotValue(await transaction.get(sdk.doc(db,"accounts",accountId))),accountId);stcAssertActiveDevice(stcSnapshotValue(await transaction.get(sdk.doc(db,"accounts",accountId,"devices",deviceId))),deviceId);const rivalry=await stcVerifyEnvelope(stcSnapshotValue(await transaction.get(sdk.doc(db,"rivalries",rivalryId))),"rivalry",rivalryId,cryptoImpl);stcEntitledRivalry(rivalry,accountId);if(rivalry.data.connectionState!=="closed")return stpFreeze({ok:true,status:"open",rivalryId,rivalryState:rivalry.data.connectionState,terminal:false});const intent=protocol.verifyIntent(rivalry.data.terminalClose);if(intent.rivalryId!==rivalryId)stpFail("TERMINAL_CLOSE_RIVALRY_MISMATCH");return stpFreeze({ok:true,status:"closed",rivalryId,rivalryState:"closed",rivalryRevision:rivalry.revision,terminal:true,terminalWitness:stpClone(intent),canonicalStorageMutation:false,listPermissionRequired:false,billingRequired:false});});}catch(error){return stcResultError(error,"TERMINAL_CLOSE_READ_FAILED");}}
  return Object.freeze({contractVersion:1,feature:"ssjr-spark-terminal-close",runtimeRevision:"1.9.1-r18",atomicRivalryAndSessionClose:true,newCollectionRequired:false,terminalReadAfterClose:true,productionRulesPublished:false,canonicalStorageMutation:false,listPermissionRequired:false,billingRequired:false,close:stcClose,read:stcRead});
});
