(function(root,factory){
  const protocol=typeof module!=="undefined"&&module.exports?require("./sharedTerminalClose.js"):root.CareerModeSharedTerminalClose;
  const sessionProtocol=typeof module!=="undefined"&&module.exports?require("./sparkPrivateSession.js"):root.CareerModeSparkPrivateSession;
  const api=factory(root,protocol,sessionProtocol);if(typeof module!=="undefined"&&module.exports)module.exports=api;else root.CareerModeSparkTerminalClose=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(root,protocol,sessionProtocol){
  "use strict";
  const RESULT_KEYS=Object.freeze(["leaguePosition","leaguePoints","leagueGoals","domesticCup","championsLeague","topScorer","topAssist"]);
  const PROGRESS_KEYS=Object.freeze(["schemaVersion","runtimeRevision","totalSeasons","acceptedThroughSeason","managerTotals","closedSessionRevision"]);
  function stpFail(code,message){const error=new Error(message||code);error.code=code;throw error;}
  function stcResultError(error,fallback){return {ok:false,code:error&&typeof error.code==="string"?error.code:fallback,message:error&&error.message?error.message:"Terminal Close could not be completed."};}
  function stpClone(value){return JSON.parse(JSON.stringify(value));}
  function stpFreeze(value){if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.values(value).forEach(stpFreeze);Object.freeze(value);}return value;}
  function stpCanonical(value){if(value===undefined||value===null)return null;if(value&&typeof value.toMillis==="function")return {$timestamp:value.toMillis()};if(value instanceof Date)return {$timestamp:value.getTime()};if(Array.isArray(value))return value.map(stpCanonical);if(typeof value==="object"){const out={};for(const key of Object.keys(value).sort())out[key]=stpCanonical(value[key]);return out;}return value;}
  function stcHex(bytes){return Array.from(bytes,value=>value.toString(16).padStart(2,"0")).join("");}
  async function stcHashEnvelopeValue(value,cryptoImpl=root.crypto){if(!cryptoImpl||!cryptoImpl.subtle||typeof cryptoImpl.subtle.digest!=="function")stpFail("TERMINAL_CLOSE_CRYPTO_UNAVAILABLE");const digest=await cryptoImpl.subtle.digest("SHA-256",new TextEncoder().encode(JSON.stringify(stpCanonical(value))));return `sha256:${stcHex(new Uint8Array(digest))}`;}
  function stcNormalizeId(value,pattern,code){const normalized=typeof value==="string"?value.trim().toLowerCase():"";if(!pattern.test(normalized))stpFail(code);return normalized;}
  function stcNormalizeAccount(user){const id=user&&typeof user.uid==="string"?user.uid.trim():"";if(!id)stpFail("TERMINAL_CLOSE_AUTH_REQUIRED");return id;}
  function stcSnapshotValue(snapshot){return snapshot&&typeof snapshot.exists==="function"&&snapshot.exists()?snapshot.data():null;}
  function stcEnvelopeShape(value,type,id){return Boolean(value&&value.schemaVersion===1&&value.objectType===type&&value.objectId===id&&Number.isInteger(value.revision)&&value.revision>=0&&value.lifecycleState==="live"&&typeof value.contentHash==="string"&&/^sha256:[0-9a-f]{64}$/.test(value.contentHash)&&value.data&&typeof value.data==="object"&&value.tombstone===null);}
  async function stcVerifyEnvelope(value,type,id,cryptoImpl){if(!stcEnvelopeShape(value,type,id))stpFail("TERMINAL_CLOSE_AUTHORITY_INVALID");const expected=await stcHashEnvelopeValue({objectType:type,objectId:id,revision:value.revision,data:value.data},cryptoImpl);if(expected!==value.contentHash)stpFail("TERMINAL_CLOSE_INTEGRITY_FAILED");return value;}
  function stcAssertActiveAccount(value,accountId){if(!stcEnvelopeShape(value,"account",accountId)||value.data.status!=="active")stpFail("TERMINAL_CLOSE_ACCOUNT_INACTIVE");}
  function stcAssertActiveDevice(value,deviceId){if(!stcEnvelopeShape(value,"device",deviceId)||value.data.deviceId!==deviceId||value.data.state!=="active")stpFail(value&&value.data&&value.data.state==="revoked"?"TERMINAL_CLOSE_DEVICE_REVOKED":"TERMINAL_CLOSE_DEVICE_INACTIVE");}
  function stcValidateSdk(firestore,sdk){if(!firestore)stpFail("TERMINAL_CLOSE_PROVIDER_UNAVAILABLE");for(const method of ["doc","runTransaction"]){if(!sdk||typeof sdk[method]!=="function")stpFail("TERMINAL_CLOSE_PROVIDER_UNAVAILABLE");}if(!sdk.Timestamp||typeof sdk.Timestamp.fromMillis!=="function")stpFail("TERMINAL_CLOSE_PROVIDER_UNAVAILABLE");}
  function stcNormalizeOptions(options={}){
    stcValidateSdk(options.firestore,options.firebaseSdk);if(!protocol||typeof protocol.verifyIntent!=="function"||!sessionProtocol||typeof sessionProtocol.verifySession!=="function"||typeof sessionProtocol.buildEnvelope!=="function")stpFail("TERMINAL_CLOSE_DEPENDENCY_UNAVAILABLE");
    const intent=protocol.verifyIntent(options.intent),rivalryId=stcNormalizeId(options.rivalryId,/^pair_[0-9a-f]{64}$/,"TERMINAL_CLOSE_RIVALRY_INVALID"),sessionId=stcNormalizeId(options.sessionId,/^session_[0-9a-f]{64}$/,"TERMINAL_CLOSE_SESSION_INVALID");
    if(intent.rivalryId!==rivalryId)stpFail("TERMINAL_CLOSE_RIVALRY_MISMATCH");if(intent.sessionId!==sessionId)stpFail("TERMINAL_CLOSE_SESSION_MISMATCH");
    const nowEpochMs=options.nowEpochMs===undefined?Date.now():Number(options.nowEpochMs);if(!Number.isFinite(nowEpochMs)||nowEpochMs<=0)stpFail("TERMINAL_CLOSE_TIME_INVALID");
    return Object.freeze({firestore:options.firestore,firebaseSdk:options.firebaseSdk,accountId:stcNormalizeAccount(options.user),deviceId:stcNormalizeId(options.deviceId,/^device_[0-9a-f]{32}$/,"TERMINAL_CLOSE_DEVICE_INVALID"),rivalryId,sessionId,intent,nowEpochMs,cryptoImpl:options.cryptoImpl||root.crypto});
  }
  function stcRefs(operation){const sdk=operation.firebaseSdk,db=operation.firestore;return Object.freeze({account:sdk.doc(db,"accounts",operation.accountId),device:sdk.doc(db,"accounts",operation.accountId,"devices",operation.deviceId),rivalry:sdk.doc(db,"rivalries",operation.rivalryId),session:sdk.doc(db,"rivalries",operation.rivalryId,"sessions",operation.sessionId),setup:sdk.doc(db,"rivalries",operation.rivalryId,"sharedSetup","authoritative"),commit:season=>sdk.doc(db,"rivalries",operation.rivalryId,"seasonCommits",`season_${season}`)});}
  function stcEntitledRivalry(rivalry,accountId){const ids=Array.isArray(rivalry.data.authorizedAccountIds)?rivalry.data.authorizedAccountIds:[],slots=Array.isArray(rivalry.data.managerSlots)?rivalry.data.managerSlots:[];if(ids.length!==2||new Set(ids).size!==2||!ids.includes(accountId)||slots.length!==2||slots.some(slot=>!slot||slot.entitlementState!=="active"||typeof slot.accountId!=="string")||!ids.every(id=>slots.some(slot=>slot.accountId===id)))stpFail("TERMINAL_CLOSE_RIVALRY_AUTHORITY_INVALID");return ids;}
  function stcExactObject(value,keys){return Boolean(value&&typeof value==="object"&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.hasOwn(value,key)));}
  function stcScoreResult(value){if(!stcExactObject(value,RESULT_KEYS))stpFail("TERMINAL_CLOSE_SEASON_COMMIT_INVALID");for(const key of ["leaguePosition","leaguePoints","leagueGoals"]){if(!Number.isInteger(value[key]))stpFail("TERMINAL_CLOSE_SEASON_COMMIT_INVALID");}if(value.leaguePosition<1||value.leaguePosition>20||value.leaguePoints<0||value.leaguePoints>114||value.leagueGoals<0||value.leagueGoals>300)stpFail("TERMINAL_CLOSE_SEASON_COMMIT_INVALID");for(const key of ["domesticCup","championsLeague","topScorer","topAssist"]){if(typeof value[key]!=="boolean")stpFail("TERMINAL_CLOSE_SEASON_COMMIT_INVALID");}return (value.championsLeague?5:0)+(value.leaguePosition===1?3:0)+(value.domesticCup?1:0)+((value.leaguePoints>=100||value.leagueGoals>=100)?1:0)+((value.topScorer||value.topAssist)?1:0);}
  function stcCommit(value,rivalryId,season){if(!value||value.schemaVersion!==1||value.objectType!=="sharedSeasonCommit"||value.rivalryId!==rivalryId||value.seasonNumber!==season||value.runtimeRevision!=="1.9.1-r10"||value.phase!=="ACKNOWLEDGED"||value.revision!==3||!stcExactObject(value.results,["playerOne","playerTwo"]))stpFail("TERMINAL_CLOSE_SEASON_COMMIT_INVALID");return Object.freeze({playerOne:stcScoreResult(value.results.playerOne),playerTwo:stcScoreResult(value.results.playerTwo)});}
  function stcSetup(value,rivalryId,totalSeasons){if(!value||value.schemaVersion!==1||value.objectType!=="sharedSetupLedger"||value.rivalryId!==rivalryId||value.revision!==6||value.phase!=="SHOWDOWN_CONFIRMED"||value.totalSeasons!==totalSeasons)stpFail("TERMINAL_CLOSE_SETUP_INVALID");return value;}
  function stcProgress(value,totalSeasons){if(!stcExactObject(value,PROGRESS_KEYS)||value.schemaVersion!==1||value.runtimeRevision!=="1.9.1-r18"||value.totalSeasons!==totalSeasons||!Number.isInteger(value.acceptedThroughSeason)||value.acceptedThroughSeason<1||value.acceptedThroughSeason>totalSeasons||!stcExactObject(value.managerTotals,["playerOne","playerTwo"])||!Number.isInteger(value.managerTotals.playerOne)||value.managerTotals.playerOne<0||!Number.isInteger(value.managerTotals.playerTwo)||value.managerTotals.playerTwo<0||(value.closedSessionRevision!==null&&(!Number.isInteger(value.closedSessionRevision)||value.closedSessionRevision<1)))stpFail("TERMINAL_CLOSE_PROGRESS_INVALID");return value;}
  async function stcBuildRivalryEnvelope(operation,prior,data,now){const revision=prior.revision+1;return {schemaVersion:1,objectType:"rivalry",objectId:operation.rivalryId,revision,parentRevision:prior.revision,lifecycleState:"live",contentHash:await stcHashEnvelopeValue({objectType:"rivalry",objectId:operation.rivalryId,revision,data},operation.cryptoImpl),priorContentHash:prior.contentHash,updatedAt:now,updatedByAccountId:operation.accountId,updatedByDeviceId:operation.deviceId,data,tombstone:null};}
  function stcAccepted(operation,rivalry,sessionRevision,replayed){return stpFreeze({ok:true,status:replayed?"replayed":"accepted",replayed:Boolean(replayed),rivalryId:operation.rivalryId,sessionId:operation.sessionId,rivalryState:"closed",sessionState:"closed",rivalryRevision:rivalry.revision,sessionRevision,terminalWitness:stpClone(operation.intent),canonicalStorageMutation:false,listPermissionRequired:false,billingRequired:false});}
  async function stcAdvanceProgress(operation,references){return operation.firebaseSdk.runTransaction(operation.firestore,async transaction=>{
    stcAssertActiveAccount(stcSnapshotValue(await transaction.get(references.account)),operation.accountId);stcAssertActiveDevice(stcSnapshotValue(await transaction.get(references.device)),operation.deviceId);
    const rivalryValue=stcSnapshotValue(await transaction.get(references.rivalry));await stcVerifyEnvelope(rivalryValue,"rivalry",operation.rivalryId,operation.cryptoImpl);stcEntitledRivalry(rivalryValue,operation.accountId);
    if(rivalryValue.data.connectionState==="closed"){if(!protocol.sameWitness(rivalryValue.data.terminalClose,operation.intent))stpFail("TERMINAL_CLOSE_REPLAY_CONFLICT");const progress=stcProgress(rivalryValue.data.terminalProgress,operation.intent.totalSeasons);if(!Number.isInteger(progress.closedSessionRevision))stpFail("TERMINAL_CLOSE_PARTIAL_STATE_INVALID");return {closed:true,done:true,rivalry:rivalryValue,sessionRevision:progress.closedSessionRevision};}
    if(rivalryValue.data.connectionState!=="active")stpFail("TERMINAL_CLOSE_RIVALRY_NOT_ACTIVE");
    const prior=rivalryValue.data.terminalProgress===undefined?null:stcProgress(rivalryValue.data.terminalProgress,operation.intent.totalSeasons);if(prior&&prior.closedSessionRevision!==null)stpFail("TERMINAL_CLOSE_PARTIAL_STATE_INVALID");if(prior&&prior.acceptedThroughSeason===operation.intent.totalSeasons)return {closed:false,done:true,rivalry:rivalryValue,progress:prior};
    const season=prior?prior.acceptedThroughSeason+1:1;if(!prior)stcSetup(stcSnapshotValue(await transaction.get(references.setup)),operation.rivalryId,operation.intent.totalSeasons);const scores=stcCommit(stcSnapshotValue(await transaction.get(references.commit(season))),operation.rivalryId,season);const nextProgress={schemaVersion:1,runtimeRevision:"1.9.1-r18",totalSeasons:operation.intent.totalSeasons,acceptedThroughSeason:season,managerTotals:{playerOne:(prior?prior.managerTotals.playerOne:0)+scores.playerOne,playerTwo:(prior?prior.managerTotals.playerTwo:0)+scores.playerTwo},closedSessionRevision:null};const now=operation.firebaseSdk.Timestamp.fromMillis(operation.nowEpochMs),nextRivalry=await stcBuildRivalryEnvelope(operation,rivalryValue,{...rivalryValue.data,terminalProgress:nextProgress},now);transaction.set(references.rivalry,nextRivalry);return {closed:false,done:season===operation.intent.totalSeasons,rivalry:nextRivalry,progress:nextProgress};
  });}
  async function stcFinalize(operation,references){return operation.firebaseSdk.runTransaction(operation.firestore,async transaction=>{
    stcAssertActiveAccount(stcSnapshotValue(await transaction.get(references.account)),operation.accountId);stcAssertActiveDevice(stcSnapshotValue(await transaction.get(references.device)),operation.deviceId);
    const rivalryValue=stcSnapshotValue(await transaction.get(references.rivalry));await stcVerifyEnvelope(rivalryValue,"rivalry",operation.rivalryId,operation.cryptoImpl);const authorized=stcEntitledRivalry(rivalryValue,operation.accountId);const progress=stcProgress(rivalryValue.data.terminalProgress,operation.intent.totalSeasons);
    if(rivalryValue.data.connectionState==="closed"){if(!protocol.sameWitness(rivalryValue.data.terminalClose,operation.intent))stpFail("TERMINAL_CLOSE_REPLAY_CONFLICT");if(!Number.isInteger(progress.closedSessionRevision))stpFail("TERMINAL_CLOSE_PARTIAL_STATE_INVALID");return stcAccepted(operation,rivalryValue,progress.closedSessionRevision,true);}
    if(rivalryValue.data.connectionState!=="active")stpFail("TERMINAL_CLOSE_RIVALRY_NOT_ACTIVE");if(progress.acceptedThroughSeason!==operation.intent.totalSeasons||progress.closedSessionRevision!==null||progress.managerTotals.playerOne!==operation.intent.managerTotals.playerOne||progress.managerTotals.playerTwo!==operation.intent.managerTotals.playerTwo)stpFail("TERMINAL_CLOSE_FINAL_AUTHORITY_MISMATCH");
    const sessionValue=stcSnapshotValue(await transaction.get(references.session));if(!sessionValue)stpFail("TERMINAL_CLOSE_SESSION_NOT_FOUND");const session=await sessionProtocol.verifySession(sessionValue,operation.rivalryId,operation.sessionId,operation.cryptoImpl);if(!session.members.includes(operation.accountId))stpFail("TERMINAL_CLOSE_SESSION_MEMBER_REQUIRED");if(session.data.state!=="active"||session.members.length!==2||authorized.some(id=>!session.members.includes(id)))stpFail("TERMINAL_CLOSE_SESSION_NOT_ACTIVE");if(operation.nowEpochMs>=session.expiresAtEpochMs)stpFail("TERMINAL_CLOSE_SESSION_EXPIRED");
    const now=operation.firebaseSdk.Timestamp.fromMillis(operation.nowEpochMs),sessionData={...session.data,state:"closed",lastActivityAt:now,revokedAt:null};const nextSession=await sessionProtocol.buildEnvelope({sessionId:operation.sessionId,revision:sessionValue.revision+1,parentRevision:sessionValue.revision,priorContentHash:sessionValue.contentHash,updatedAt:now,accountId:operation.accountId,deviceId:operation.deviceId,data:sessionData,cryptoImpl:operation.cryptoImpl});const nextProgress={...stpClone(progress),closedSessionRevision:nextSession.revision};const rivalryData={...rivalryValue.data,connectionState:"closed",terminalProgress:nextProgress,terminalClose:stpClone(operation.intent)},nextRivalry=await stcBuildRivalryEnvelope(operation,rivalryValue,rivalryData,now);transaction.set(references.session,nextSession);transaction.set(references.rivalry,nextRivalry);return stcAccepted(operation,nextRivalry,nextSession.revision,false);
  });}
  async function stcClose(options={}){try{const operation=stcNormalizeOptions(options),references=stcRefs(operation);for(let step=0;step<=operation.intent.totalSeasons;step++){const progress=await stcAdvanceProgress(operation,references);if(progress.closed)return stcAccepted(operation,progress.rivalry,progress.sessionRevision,true);if(progress.done)break;if(step===operation.intent.totalSeasons)stpFail("TERMINAL_CLOSE_PROGRESS_STALLED");}return await stcFinalize(operation,references);}catch(error){return stcResultError(error,"TERMINAL_CLOSE_FAILED");}}
  async function stcRead(options={}){try{stcValidateSdk(options.firestore,options.firebaseSdk);if(!protocol||typeof protocol.verifyIntent!=="function")stpFail("TERMINAL_CLOSE_DEPENDENCY_UNAVAILABLE");const accountId=stcNormalizeAccount(options.user),deviceId=stcNormalizeId(options.deviceId,/^device_[0-9a-f]{32}$/,"TERMINAL_CLOSE_DEVICE_INVALID"),rivalryId=stcNormalizeId(options.rivalryId,/^pair_[0-9a-f]{64}$/,"TERMINAL_CLOSE_RIVALRY_INVALID"),cryptoImpl=options.cryptoImpl||root.crypto,sdk=options.firebaseSdk,db=options.firestore;return await sdk.runTransaction(db,async transaction=>{stcAssertActiveAccount(stcSnapshotValue(await transaction.get(sdk.doc(db,"accounts",accountId))),accountId);stcAssertActiveDevice(stcSnapshotValue(await transaction.get(sdk.doc(db,"accounts",accountId,"devices",deviceId))),deviceId);const rivalry=await stcVerifyEnvelope(stcSnapshotValue(await transaction.get(sdk.doc(db,"rivalries",rivalryId))),"rivalry",rivalryId,cryptoImpl);stcEntitledRivalry(rivalry,accountId);if(rivalry.data.connectionState!=="closed")return stpFreeze({ok:true,status:"open",rivalryId,rivalryState:rivalry.data.connectionState,terminal:false});const intent=protocol.verifyIntent(rivalry.data.terminalClose),progress=stcProgress(rivalry.data.terminalProgress,intent.totalSeasons);if(intent.rivalryId!==rivalryId||progress.acceptedThroughSeason!==progress.totalSeasons||progress.managerTotals.playerOne!==intent.managerTotals.playerOne||progress.managerTotals.playerTwo!==intent.managerTotals.playerTwo||!Number.isInteger(progress.closedSessionRevision))stpFail("TERMINAL_CLOSE_RIVALRY_MISMATCH");return stpFreeze({ok:true,status:"closed",rivalryId,rivalryState:"closed",rivalryRevision:rivalry.revision,sessionRevision:progress.closedSessionRevision,terminal:true,terminalWitness:stpClone(intent),canonicalStorageMutation:false,listPermissionRequired:false,billingRequired:false});});}catch(error){return stcResultError(error,"TERMINAL_CLOSE_READ_FAILED");}}
  return Object.freeze({contractVersion:1,feature:"ssjr-spark-terminal-close",runtimeRevision:"1.9.1-r18",atomicRivalryAndSessionClose:true,stagedTerminalProof:true,maxTerminalProofSteps:10,newCollectionRequired:false,terminalReadAfterClose:true,productionRulesPublished:false,canonicalStorageMutation:false,listPermissionRequired:false,billingRequired:false,close:stcClose,read:stcRead});
});