#!/usr/bin/env python3
"""Rebuild BOARD.md from BOARD.json and status/JOB-NN.md. Run from the repo root:
    python3 project-documents/gameplay-factory/tools/board.py
Prints what can start now in each lane."""
import json, os, re, datetime

F = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
board = json.load(open(os.path.join(F, "BOARD.json")))
jobs = board["jobs"]
by_num = {j["number"]: j for j in jobs}
FINISHED = ("DONE", "SKIPPED")


def read_status(j):
    p = os.path.join(F, "status", f"JOB-{j['number']:02d}.md")
    if not j.get("written") or not os.path.exists(p):
        return "NOT WRITTEN", 0, j.get("steps") or 1
    txt = open(p).read()
    st = re.search(r"^State:\s*(.+)$", txt, re.M)
    sp = re.search(r"^Step:\s*(\d+)\s*of\s*(\d+)", txt, re.M)
    state = st.group(1).strip().upper() if st else "NOT STARTED"
    if state == "READY":
        state = "NOT STARTED"
    k, total = (int(sp.group(1)), int(sp.group(2))) if sp else (0, j.get("steps") or 1)
    return state, k, total


info = {j["number"]: read_status(j) for j in jobs}


def pct(n):
    state, k, total = info[n]
    return 100 if state in FINISHED else int(100 * k / max(total, 1))


def bar(p):
    return "█" * (p // 10) + "░" * (10 - p // 10)


def ready(j):
    return info[j["number"]][0] == "NOT STARTED" and all(info[d][0] in FINISHED for d in j["depends_on"])


cap = board.get("capacity", {"chat": 2, "work": 1})
busy = [j for j in jobs if info[j["number"]][0].startswith("IN PROGRESS")]
free = {lane: max(0, cap.get(lane, 0) - sum(1 for j in busy if j["lane"] == lane)) for lane in ("chat", "work")}
start = {"chat": [], "work": []}
queued = []
for j in jobs:
    if not ready(j) or j["lane"] not in start:
        continue
    if len(start[j["lane"]]) < free[j["lane"]]:
        start[j["lane"]].append(j["number"])
    else:
        queued.append(j["number"])

worker_jobs = [j for j in jobs if j["lane"] in ("chat", "work")]
done = sum(1 for j in jobs if info[j["number"]][0] in FINISHED)
overall = sum(pct(j["number"]) for j in jobs) // len(jobs)
names = lambda xs: ", ".join(map(str, xs)) or "-"
working = [j["number"] for j in busy]
blocked = [j["number"] for j in jobs if info[j["number"]][0].startswith("BLOCKED")]
waiting = [j for j in jobs if info[j["number"]][0].startswith("WAITING")]

L = ["# Team G gameplay factory board", "",
     f"Branch `{board['branch']}` · code PRs into `{board['integration_branch']}` · generated {datetime.datetime.utcnow():%Y-%m-%d %H:%M} UTC", "",
     f"**Overall:** {bar(overall)} {overall} % · {done} of {len(jobs)} jobs done", "",
     f"**Start now in a normal chat (press Stay in Chat):** {names(start['chat'])}", "",
     f"**Start now in Sol Work mode (press Use Work, paste the starter line from RULES.md):** {names(start['work'])}", ""]
if queued:
    L += [f"**Ready but no free slot yet:** {names(queued)}", ""]
L += [f"**Working:** {names(working)} · **Blocked:** {names(blocked)}", ""]
if waiting:
    L += ["**Waiting:** " + "; ".join(f"{j['number']} ({info[j['number']][0].lower()})" for j in waiting), ""]
L += ["| # | G id | Job | Lane | Depends on | Codex | Progress | State |", "| --- | --- | --- | --- | --- | --- | --- | --- |"]
for j in jobs:
    n = j["number"]
    title = f"[{j['title']}](jobs/JOB-{n:02d}.md)" if j.get("written") else j["title"]
    dep = names(j["depends_on"]) + (f"; {j['waits_on']}" if j.get("waits_on") else "")
    L.append(f"| {n} | {j['key']} | {title} | {j['lane']} | {dep} | {'yes' if j['codex_review'] else ''} | {bar(pct(n))} {pct(n)} % | {info[n][0]} |")
L += ["", "Lanes: **chat** = normal GPT-5.6 Sol chat (text, local Chromium, no reliable npm); **work** = Sol Work mode (terminal, no browser); **nik** = Nik on his real devices. NOT WRITTEN = the lead has not written the job file yet; never start it.",
      "", f"Capacity: {cap.get('chat')} normal chats and {cap.get('work')} Work-mode chat at once for Team G.",
      "", "Generated by `project-documents/gameplay-factory/tools/board.py` from `BOARD.json` and `status/`. Workers never edit this file."]
open(os.path.join(F, "BOARD.md"), "w").write("\n".join(L) + "\n")
print("start chat:", start["chat"], "start work:", start["work"], "queued:", queued, "overall:", overall, "%")
